In [6]:
#topics on numpy
import numpy as np # Import the numpy package as np
# Creating array object 
arr = np.array( [[ 1, 2, 3], [ 4, 2, 5]] )

print("Array is of type: ", type(arr)) # Printing type of arr object
print("No. of dimensions: ", arr.ndim) # Printing array dimensions
print("Shape of array: ", arr.shape)   # Printing shape of array
print("Size of array: ", arr.size)     # Printing size (total number of elements) of array
  

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


In [18]:
weights=[ 50.00, 77.77, 98.18, 18.89, 55.98, 80.09 , 45.90] #creaing lists weights and heights
heights=[ 5.3, 6.1, 4.7, 5.4, 6.3 ,4.9, 5.7]

import numpy as np  # Import the numpy package as np

height=np.array(heights)
weight=np.array(weights)

print(type(height))

bim= height/weight**2 # calculating bim
print(bim)





<class 'numpy.ndarray'>
[0.00212    0.00100857 0.00048759 0.01513317 0.00201036 0.00076391
 0.00270551]


In [23]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Creating a numpy array weight from weight_kg
weight=np.array(weight_kg)
# Creating weight_lbs from weight
weight_lbs=weight/0.453592
# Printing results in weight_lbs
print("Here,all given weight in lbs is:",weight_lbs)

Here,all given weight in lbs is: [180.00758391 214.99497346 209.99047602 204.98597859 189.99453253
 194.99902997]


In [28]:
import numpy as np
data_for_series=np.random.randint(0,77,size=(7)) # here it gives the 7 random numbers from 0 to 77
print(data_for_series)

data=np.random.randint(0,9,(3,4)) #it shows the random number  from o to 9 in 3*4 imensional matrix form
print(data)

[11 60 30 27 51  6  9]
[[2 7 2 2]
 [5 4 8 6]
 [4 1 1 8]]


In [5]:
#examples in pandas
 
import pandas as pd 
 
# list of strings
lists = ['python', 'is', 'popular', 'language','nowadays', 'for', 'learn']
 
# Calling DataFrame constructor on list
df = pd.DataFrame(lists)
print(df)


          0
0    python
1        is
2   popular
3  language
4  nowadays
5       for
6     learn


In [6]:
import pandas as pd
 
# intialise data of lists.
data = {'Name':['sandesh', 'aakash', 'prem', 'prabodh'],
        'Age':[21, 23, 22, 21]}
 
# Create DataFrame
df = pd.DataFrame(data)
 
# Print the output.
print(df)

      Name  Age
0  sandesh   21
1   aakash   23
2     prem   22
3  prabodh   21


In [11]:
dict = {"country": ["Portugal", "Spain", "Nepal", "Australia", "Germany"],
       "capital": ["Lisbon", "Madrid", "Kathmandu", "Canberra", "Munich"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

import pandas as pd
datas = pd.DataFrame(dict)
print(datas)

 

     country    capital    area  population
0   Portugal     Lisbon   8.516      200.40
1      Spain     Madrid  17.100      143.50
2      Nepal  Kathmandu   3.286     1252.00
3  Australia   Canberra   9.597     1357.00
4    Germany     Munich   1.221       52.98


In [12]:
print(datas[['country', 'capital']]) #printing two columns from dictionary "country" and "capital" from above dict

     country    capital
0   Portugal     Lisbon
1      Spain     Madrid
2      Nepal  Kathmandu
3  Australia   Canberra
4    Germany     Munich


In [14]:
datas.index=["POR","ESP","NEP","AUS","GER"] #giving index in above datas from dict(dictionary)
print(datas)

       country    capital    area  population
POR   Portugal     Lisbon   8.516      200.40
ESP      Spain     Madrid  17.100      143.50
NEP      Nepal  Kathmandu   3.286     1252.00
AUS  Australia   Canberra   9.597     1357.00
GER    Germany     Munich   1.221       52.98


In [8]:
import pandas as pd

# making data frame from  iris csv file from folder
data = pd.read_csv("iris.csv")

first = data["sepal_length"] #here first = sepal length only from the data frame.so,it prints sepal length only from data
second=data
print(first,"\n\n\n",second) #here second prints the all data of data frame and "\n\n\n" for the space in the output
                             #or for the line breaking


0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64 


      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [11]:
#import pandas as pd
#data=pd.read_csv("iris.csv")
 
print(data[0:4]) # Print out first 4 observations

 
print(data[7:18]) # Print out seventh to eighteen observation from given data frame

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
    sepal_length  sepal_width  petal_length  petal_width species
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9 

In [16]:

print(data.iloc[2])


print(data.loc[['petal_width', 'species']]) 

sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object


KeyError: "None of [Index(['petal_width', 'species'], dtype='object')] are in the [index]"